Add checks for Docker

diff --git a/tests/fixtures/mkdat b/tests/fixtures/mkdat
--- a/tests/fixtures/mkdat
+++ b/tests/fixtures/mkdat
@@ -4,6 +4,12 @@ set -e
 set -u
 set -o pipefail
 
+if ! command -v docker &> /dev/null
+then
+  printf '%s\n' 'Docker is required but missing' 1>&2
+  exit 1
+fi
+
 wordlist_image=$(docker build --quiet - <<EOF
 FROM ubuntu:20.04
 RUN apt-get update && apt-get -qqq install wcanadian-huge
diff --git a/tests/nginx/start b/tests/nginx/start
--- a/tests/nginx/start
+++ b/tests/nginx/start
@@ -4,6 +4,12 @@ set -e
 set -u
 set -o pipefail
 
+if ! command -v docker &> /dev/null
+then
+  printf '%s\n' 'Docker is required but missing' 1>&2
+  exit 1
+fi
+
 # This comes via `yarn run`
 # shellcheck disable=SC2154
 exec docker run --rm --name "${npm_package_name}-nginx" \
